### ISSUE TITLE
Support for inline list rendering

### ISSUE THREAD

**Issue by lyonssp** [jcazevedo/moultingyaml#37]
I want to serialize my yaml list inline, rather than producing to the more common multi-line rendering.

Want:
```yaml
foo:
  list: [this, list, of, stuff]
```

Default: 
```yaml
foo:
  list:
  - this
  - list
  - of
  - stuff
```

It doesn't seem like this kind of serialization is documented, but I was wondering if it is supported at all.

More broadly, is there a way to hook into the printing process to dictate how `YamlValue` objects are rendered?
